//! FR-15 图标资产集成 (ADR-18③): **存在才嵌入** —— CI 三平台不依赖美术文件。
//!
//! 职责:
//! 1. exe 图标 (仅 Windows 目标, winres 嵌 assets/app.ico);
//! 2. 把托盘三态 / 窗口图标 PNG 在**构建期**解码成原始 RGBA 写进 OUT_DIR
//!    (运行时零解码依赖: gui.rs 直接 Icon::from_rgba), 缺资产 → 对应常量为 None
//!    (运行时回退程序内绘制的圆点);
//! 3. 窗口图标源优先级: app.ico 内最大 PNG 条目 → png/serialhub-64.png;
//! 4. 生成 OUT_DIR/embedded_icons.rs 供 src/icons.rs include!
//!    (无论资产是否齐全都写出该文件, include! 永不失败);
//! 5. favicon.svg 按文本嵌入 (存在才有 Some)。
//!
//! 资产契约见 assets/README.md。

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=assets");
    println!("cargo:rerun-if-changed=build.rs");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // 1) exe 图标: winres 仅对 Windows 目标执行 (非 Windows 目标不引用 winres 逻辑)
    let ico = Path::new("assets/app.ico");
    if target_os == "windows" && ico.exists() {
        if let Err(e) = winres::WindowsResource::new().set_icon("assets/app.ico").compile() {
            println!("cargo:warning=SerialHub: app.ico 嵌入失败 (忽略, exe 无自定义图标): {e}");
        }
    }

    // 2/3) 解码 RGBA (构建期; 失败一律回退 None, 不阻塞构建)
    let window = decode_window_icon();
    let tray_open = decode_png(Path::new("assets/tray-open.png"));
    let tray_retry = decode_png(Path::new("assets/tray-retry.png"));
    let tray_closed = decode_png(Path::new("assets/tray-closed.png"));

    // 4) 生成嵌入清单 (恒定写出)
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let gen = |payload: &Option<(Vec<u8>, u32, u32)>, name: &str| -> String {
        match payload {
            Some((rgba, w, h)) => {
                let bin = out_dir.join(format!("{name}.rgba"));
                fs::write(&bin, rgba)
                    .unwrap_or_else(|e| panic!("写 OUT_DIR/{name}.rgba 失败: {e}"));
                format!(
                    "pub(crate) const {name}: Option<RgbaIcon> = \
                     Some((include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{name}.rgba\")), {w}, {h}));\n"
                )
            }
            None => format!("pub(crate) const {name}: Option<RgbaIcon> = None;\n"),
        }
    };
    let mut code = String::from("// @generated by build.rs (FR-15) —— 资产存在才嵌入, 请勿手改\n");
    code.push_str("pub(crate) type RgbaIcon = (&'static [u8], u32, u32);\n");
    code.push_str(&gen(&window, "WINDOW_ICON_RGBA"));
    code.push_str(&gen(&tray_open, "TRAY_OPEN_RGBA"));
    code.push_str(&gen(&tray_retry, "TRAY_RETRY_RGBA"));
    code.push_str(&gen(&tray_closed, "TRAY_CLOSED_RGBA"));
    // favicon: 文本资产, 直接 include_str! 源文件 (存在才生成 Some 分支)
    code.push_str(&match fs::read_to_string("assets/favicon.svg") {
        Ok(_) => "pub(crate) const FAVICON_SVG: Option<&'static str> = Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/favicon.svg\")));\n".to_string(),
        Err(_) => "pub(crate) const FAVICON_SVG: Option<&'static str> = None;\n".to_string(),
    });
    fs::write(out_dir.join("embedded_icons.rs"), code).expect("写 embedded_icons.rs 失败");
}

/// 窗口图标: app.ico 内最大 PNG 条目优先, 回退 png/serialhub-64.png (契约见 README)。
fn decode_window_icon() -> Option<(Vec<u8>, u32, u32)> {
    let bytes = fs::read("assets/app.ico").ok()?;
    match largest_png_from_ico(&bytes).and_then(|png| decode_png_bytes(png)) {
        Some(v) => Some(v),
        None => decode_png(Path::new("assets/png/serialhub-64.png")),
    }
}

/// ICO 目录解析: 返回**最大**的 PNG 压缩条目 (纯 BMP 条目跳过, 见 README 契约)。
fn largest_png_from_ico(bytes: &[u8]) -> Option<&[u8]> {
    if bytes.len() < 6 || bytes[0] != 0 || bytes[1] != 0 || bytes[2] != 1 {
        return None;
    }
    let count = u16::from_le_bytes([bytes[4], bytes[5]]) as usize;
    let mut best: Option<(u32, usize, usize)> = None; // (面积, 偏移, 长度)
    for i in 0..count {
        let e = 6 + i * 16;
        if e + 16 > bytes.len() {
            return None;
        }
        let w = if bytes[e] == 0 { 256 } else { bytes[e] as u32 };
        let h = if bytes[e + 1] == 0 { 256 } else { bytes[e + 1] as u32 };
        let len = u32::from_le_bytes(bytes[e + 8..e + 12].try_into().ok()?) as usize;
        let off = u32::from_le_bytes(bytes[e + 12..e + 16].try_into().ok()?) as usize;
        if off + len > bytes.len() {
            continue;
        }
        if bytes[off..off + 4] != [0x89, b'P', b'N', b'G'] {
            continue; // BMP 条目不支持
        }
        if best.map_or(true, |(a, _, _)| w * h > a) {
            best = Some((w * h, off, len));
        }
    }
    best.map(|(_, off, len)| &bytes[off..off + len])
}

fn decode_png(path: &Path) -> Option<(Vec<u8>, u32, u32)> {
    let bytes = fs::read(path).ok()?;
    decode_png_bytes(&bytes)
}

/// PNG → 8bit RGB/RGBA → RGBA 原始像素 (行序, 与 Icon::from_rgba 口径一致)。
fn decode_png_bytes(bytes: &[u8]) -> Option<(Vec<u8>, u32, u32)> {
    let mut dec = png::Decoder::new(std::io::Cursor::new(bytes));
    dec.set_transformations(png::Transformations::EXPAND); // 调色板/灰度 → RGB(A)
    let mut rdr = dec.read_info().ok()?;
    let mut buf = vec![0u8; rdr.output_buffer_size()];
    let info = rdr.next_frame(&mut buf).ok()?;
    let (w, h) = (info.width, info.height);
    if w == 0 || h == 0 || (w as u64) * (h as u64) > 4096 * 4096 {
        return None;
    }
    let (color, _depth) = rdr.output_color_type();
    if info.bit_depth != png::BitDepth::Eight {
        return None;
    }
    let raw = &buf[..info.buffer_size()];
    let rgba = match color {
        png::ColorType::Rgba => raw.to_vec(),
        png::ColorType::Rgb => {
            let mut v = Vec::with_capacity(raw.len() / 3 * 4);
            for px in raw.chunks_exact(3) {
                v.extend_from_slice(px);
                v.push(255);
            }
            v
        }
        _ => return None,
    };
    if rgba.len() != (w as usize) * (h as usize) * 4 {
        return None;
    }
    Some((rgba, w, h))
}
